require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/**/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false
  Exclude:
    - bin/*

RSpec/ExampleLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/LambdaCall:
  EnforcedStyle: brances
